#!/bin/sh

set -e

if type compare > /dev/null; then
    true
else
    echo "WARN: compare from ImageMagick not found, cannot run tests"
    exit 0
fi

CSVG="./SvgContouring"

INDIR="`dirname $0`/contour_data"
OUTDIR="contour_data"

if test ! -e "$CSVG"; then
    echo "FAIL: executable $CSVG missing in `pwd`"
    exit 1
fi

mkdir -p "$OUTDIR"

FAIL=""

test_pass() {
    echo "      OK contour line test '$1'"
}
test_fail() {
    echo "MISMATCH contour line test '$1'"
    FAIL="yes"
}
test_compare() {
    EX="$1"
    AC="$2"

    DIFF_AE="`compare -metric AE $EX $AC /tmp/compare.png 2>&1`"
    test "$DIFF_AE" -eq 0
}

run_test() {
    IN="test_$1.dat"
    EX="expected_$1.svg"
    AC="actual_$1.svg"
    
    if test -r "$INDIR/$IN" -a -r "$INDIR/$EX"; then
        "$CSVG" "$INDIR/$IN" "$OUTDIR/$AC"
        if test_compare "$INDIR/$EX" "$OUTDIR/$AC"; then
            test_pass "$1"
            return
        fi
    fi
    test_fail "$1"
}

for t in empty top1 bottom1 left1 right1 sq1 sq2 lsq ll rsq rr tsq tt bsq bb hor_up \
    hor_back_up hor_down r_down r_down2 inset G border_inset_left border_inset_right \
    corner_bl corner_br corner_tl corner_tr many; do
    run_test $t
done

if test -n "$FAIL"; then
    exit 1
else
    exit 0
fi
