docdir= $(datarootdir)/doc/diana-@PVERSION@
dist_doc_DATA= share/doc/diana/vprofWindow.png \
	share/doc/diana/vprofSetup.png \
	share/doc/diana/vprofSetup2.png \
	share/doc/diana/vprofModel.png \
	share/doc/diana/vcTool.png \
	share/doc/diana/vcrossWindow.png \
	share/doc/diana/vcrossSetup.png \
	share/doc/diana/vcross.png \
	share/doc/diana/vcrossDialog.png \
	share/doc/diana/vcrossDialogAdvanced.png \
	share/doc/diana/ug_verticalprofiles.html \
	share/doc/diana/ug_verticalcrosssections.html \
	share/doc/diana/ug_vcrossfunctions.html \
	share/doc/diana/ug_trajectories.html \
	share/doc/diana/ug_timecontrol.html \
	share/doc/diana/ug_statusline.html \
	share/doc/diana/ug_spectrum.html \
	share/doc/diana/ug_shortcutkeys.html \
	share/doc/diana/ug_setupfile.html \
	share/doc/diana/ug_satdialogue.html \
	share/doc/diana/ug_stationdialogue.html \
	share/doc/diana/ug_quickmenu.html \
	share/doc/diana/ug_profetdrawingtools.html \
	share/doc/diana/ug_obsdialogue.html \
	share/doc/diana/ug_objectdialogue.html \
	share/doc/diana/ug_mapdialogue.html \
	share/doc/diana/ug_mainwindow.html \
	share/doc/diana/ug_information.html \
	share/doc/diana/ug_fileformats.html \
	share/doc/diana/ug_fieldfunctions.html \
	share/doc/diana/ug_fielddialogue.html \
	share/doc/diana/ug_editdialogue.html \
	share/doc/diana/ug_bdiana.html \
	share/doc/diana/uffda.html \
	share/doc/diana/trajectory_icon.png \
	share/doc/diana/trajectorydialogue.png \
	share/doc/diana/toolbar.png \
	share/doc/diana/toolbar1.png \
	share/doc/diana/timetoolbar.png \
	share/doc/diana/timeslider.png \
	share/doc/diana/thumbsup.png \
	share/doc/diana/textbox.png \
	share/doc/diana/takeover.png \
	share/doc/diana/synop_red.png \
	share/doc/diana/stop.png \
	share/doc/diana/status.png \
	share/doc/diana/spectrumWindow.png \
	share/doc/diana/spectrumSetup.png \
	share/doc/diana/spectrum.png \
	share/doc/diana/spectrumModel.png \
	share/doc/diana/sigtextsymbol.png \
	share/doc/diana/sigtext3.png \
	share/doc/diana/sigtext2.png \
	share/doc/diana/sigtext1.png \
	share/doc/diana/sigsymbol7.png \
	share/doc/diana/sigsymbol16.png \
	share/doc/diana/send.png \
	share/doc/diana/savestate.png \
	share/doc/diana/savemenu.png \
	share/doc/diana/sat.png \
	share/doc/diana/satellitedialogue.png \
	share/doc/diana/satellitedialogue_more.png \
	share/doc/diana/sat_arrows.png \
	share/doc/diana/station.png \
	share/doc/diana/stationdialogue.png \
	share/doc/diana/quick.png \
	share/doc/diana/quickoptionsdialogue.png \
	share/doc/diana/quickeditdialogue.png \
	share/doc/diana/quickdialogue.png \
	share/doc/diana/observations.png \
	share/doc/diana/observationdialogue_criteria.png \
	share/doc/diana/observationdialogue2.png \
	share/doc/diana/observationdialogue1.png \
	share/doc/diana/objectsfrom.png \
	share/doc/diana/objectdialogue.png \
	share/doc/diana/nmf.html \
	share/doc/diana/news.html \
	share/doc/diana/newproduct.png \
	share/doc/diana/newcombine.png \
	share/doc/diana/menubar.png \
	share/doc/diana/map_icon.png \
	share/doc/diana/mapdialogue.png \
	share/doc/diana/mainwindow.png \
	share/doc/diana/loop.png \
	share/doc/diana/level_arrows.png \
	share/doc/diana/info.png \
	share/doc/diana/index.html \
	share/doc/diana/front_icon.png \
	share/doc/diana/forwards.png \
	share/doc/diana/form.png \
	share/doc/diana/field_icon.png \
	share/doc/diana/fieldfrom.png \
	share/doc/diana/field-difference.png \
	share/doc/diana/fielddialogue.png \
	share/doc/diana/fielddialogue-advanced.png \
	share/doc/diana/fieldbuttons3.png \
	share/doc/diana/fieldbuttons2.png \
	share/doc/diana/fieldbuttons1.png \
	share/doc/diana/edittext.png \
	share/doc/diana/editstarttime.png \
	share/doc/diana/editsigmap.png \
	share/doc/diana/editing4.png \
	share/doc/diana/editing3.png \
	share/doc/diana/editing2.png \
	share/doc/diana/editing1.png \
	share/doc/diana/edit_icon.png \
	share/doc/diana/draw9.png \
	share/doc/diana/draw8.png \
	share/doc/diana/draw7.png \
	share/doc/diana/draw6.png \
	share/doc/diana/draw5.png \
	share/doc/diana/draw4.png \
	share/doc/diana/draw3.png \
	share/doc/diana/draw2.png \
	share/doc/diana/draw1.png \
	share/doc/diana/draw19.png \
	share/doc/diana/draw18.png \
	share/doc/diana/draw17.png \
	share/doc/diana/draw16.png \
	share/doc/diana/draw15.png \
	share/doc/diana/draw14.png \
	share/doc/diana/draw13.png \
	share/doc/diana/draw12.png \
	share/doc/diana/draw11.png \
	share/doc/diana/draw10.png \
	share/doc/diana/disconn.png \
	share/doc/diana/dianaVprof.png \
	share/doc/diana/dianaVcross.png \
	share/doc/diana/dianaSpectrum.png \
	share/doc/diana/diana.png \
	share/doc/diana/diana_logo.png \
	share/doc/diana/conn.png \
	share/doc/diana/comment1.png \
	share/doc/diana/clock.png \
	share/doc/diana/classtable.png \
	share/doc/diana/balloon_icon.png \
	share/doc/diana/backwards.png \
	share/doc/diana/arrow.png \
	share/doc/diana/archive_icon.png \
	share/doc/diana/anim_forwards.png \
	share/doc/diana/anim_backwards.png \
	share/doc/diana/animation.png \
	share/doc/diana/altmenu.png
