productsdir= $(datarootdir)/$(APP)/products
dist_products_DATA= share/diana/products/swikart.txt \
	share/diana/products/SKVkart.txt \
	share/diana/products/sigkart.txt \
	share/diana/products/sigkarta_SodraFlyg.txt \
	share/diana/products/sigkarta_SodraArlanda.txt \
	share/diana/products/analys_Europa.txt \
	share/diana/products/prognose+36.txt \
	share/diana/products/prognose+18.txt \
	share/diana/products/iskart.txt \
	share/diana/products/bakkeanalyse.txt \
	share/diana/products/ANAborders.TEST \
	share/diana/products/ANAborders.DNMI

fontsdir= $(datarootdir)/$(APP)/fonts
dist_fonts_DATA= share/diana/fonts/metsymbols.ttf \
	share/diana/fonts/Linedraw.ttf \
	share/diana/fonts/dnmimet.ttf \
	share/diana/fonts/Cour.ttf \
	share/diana/fonts/Couri.ttf \
	share/diana/fonts/Courbi.ttf \
	share/diana/fonts/Courbd.ttf \
	share/diana/fonts/Arial.ttf \
	share/diana/fonts/Arialn.ttf \
	share/diana/fonts/Arialni.ttf \
	share/diana/fonts/Arialnb.ttf \
	share/diana/fonts/Arialnbi.ttf \
	share/diana/fonts/Ariali.ttf \
	share/diana/fonts/Arialbi.ttf \
	share/diana/fonts/Arialbd.ttf \
	share/diana/fonts/Vera.ttf \
	share/diana/fonts/VeraIt.ttf \
	share/diana/fonts/VeraBI.ttf \
	share/diana/fonts/VeraBd.ttf

imagesdir= $(datarootdir)/$(APP)/images
dist_images_DATA= share/diana/images/wwwmet7_transp.png \
	share/diana/images/wwwmet7.png \
	share/diana/images/wwwmet4.png \
	share/diana/images/wwwmet4_nontrans.png \
	share/diana/images/wind30.png \
	share/diana/images/vprof_selected.xpm \
	share/diana/images/vprof_selected.png \
	share/diana/images/vprof_normal.xpm \
	share/diana/images/vprof_normal.png \
	share/diana/images/Text_1.png \
	share/diana/images/Tekst_2.png \
	share/diana/images/Tekst_1.png \
	share/diana/images/spectrum_selected.xpm \
	share/diana/images/spectrum_selected.png \
	share/diana/images/spectrum_normal.xpm \
	share/diana/images/spectrum_normal.png \
	share/diana/images/small_metno_sort.png \
	share/diana/images/Sig_fzfg.png \
	share/diana/images/Sig_fg.png \
	share/diana/images/Sig_br.png \
	share/diana/images/Sig9.png \
	share/diana/images/Sig8.png \
	share/diana/images/Sig7.png \
	share/diana/images/Sig6.png \
	share/diana/images/Sig5.png \
	share/diana/images/Sig4.png \
	share/diana/images/Sig3.png \
	share/diana/images/Sig39.png \
	share/diana/images/Sig38.png \
	share/diana/images/Sig37.png \
	share/diana/images/Sig36.png \
	share/diana/images/Sig35.png \
	share/diana/images/Sig34.png \
	share/diana/images/Sig33.png \
	share/diana/images/Sig32.png \
	share/diana/images/Sig31.png \
	share/diana/images/Sig30.png \
	share/diana/images/Sig2.png \
	share/diana/images/Sig29.png \
	share/diana/images/Sig28.png \
	share/diana/images/Sig27.png \
	share/diana/images/Sig26.png \
	share/diana/images/Sig25.png \
	share/diana/images/Sig24.png \
	share/diana/images/Sig23.png \
	share/diana/images/Sig22.png \
	share/diana/images/Sig21.png \
	share/diana/images/Sig20.png \
	share/diana/images/Sig1.png \
	share/diana/images/Sig19.png \
	share/diana/images/Sig18.png \
	share/diana/images/Sig17.png \
	share/diana/images/Sig16.png \
	share/diana/images/Sig15.png \
	share/diana/images/Sig14.png \
	share/diana/images/Sig13.png \
	share/diana/images/Sig12.png \
	share/diana/images/Sig11.png \
	share/diana/images/Sig10.png \
	share/diana/images/Snow.png \
	share/diana/images/Snow_showers.png \
	share/diana/images/Showers.png \
	share/diana/images/Drizzle.png \
	share/diana/images/Freezing_drizzle.png \
	share/diana/images/Hails.png \
	share/diana/images/Snow_rain.png \
	share/diana/images/Snow_rain_showers.png \
	share/diana/images/Corn_snow.png \
	share/diana/images/seastate10.png \
	share/diana/images/sea10.png \
	share/diana/images/reducedVis.png \
	share/diana/images/precip.png \
	share/diana/images/metpos.png \
	share/diana/images/metno_sort_txt.png \
	share/diana/images/metno_sort_txt_big.png \
	share/diana/images/metno_sort_txt_big2.png \
	share/diana/images/metno_sort.png \
	share/diana/images/metno.png \
	share/diana/images/fzfg.png \
	share/diana/images/fog.png \
	share/diana/images/dnmi.xpm \
	share/diana/images/dnmi.png 

markersdir= $(datarootdir)/$(APP)/images/markers
dist_markers_DATA= share/diana/images/markers/x.xpm \
	share/diana/images/markers/x.txt \
	share/diana/images/markers/wbkz_yellow.xpm \
	share/diana/images/markers/wbkz_white.xpm \
	share/diana/images/markers/wbkz_red.xpm \
	share/diana/images/markers/wbkz_orange.xpm \
	share/diana/images/markers/wbkz_green.xpm \
	share/diana/images/markers/triangle.xpm \
	share/diana/images/markers/triangle.txt \
	share/diana/images/markers/square.xpm \
	share/diana/images/markers/square.txt \
	share/diana/images/markers/square_filled.xpm \
	share/diana/images/markers/square_filled.txt \
	share/diana/images/markers/small_square.xpm \
	share/diana/images/markers/small_square.txt \
	share/diana/images/markers/lyn.xpm \
	share/diana/images/markers/lyn.txt \
	share/diana/images/markers/cc_yellow.xpm \
	share/diana/images/markers/cc_yellow_trend.xpm \
	share/diana/images/markers/cc_yellow_obs.xpm \
	share/diana/images/markers/cc_white.xpm \
	share/diana/images/markers/cc_white_trend.xpm \
	share/diana/images/markers/cc_white_obs.xpm \
	share/diana/images/markers/cc_red.xpm \
	share/diana/images/markers/cc_red_trend.xpm \
	share/diana/images/markers/cc_red_obs.xpm \
	share/diana/images/markers/cc_green.xpm \
	share/diana/images/markers/cc_green_trend.xpm \
	share/diana/images/markers/cc_green_obs.xpm \
	share/diana/images/markers/cc_blue.xpm \
	share/diana/images/markers/cc_blue_trend.xpm \
	share/diana/images/markers/cc_blue_obs.xpm \
	share/diana/images/markers/cc_black.xpm \
	share/diana/images/markers/cc_black_trend.xpm \
	share/diana/images/markers/cc_black_obs.xpm \
	share/diana/images/markers/cc_amber.xpm \
	share/diana/images/markers/cc_amber_trend.xpm \
	share/diana/images/markers/cc_amber_obs.xpm 

patternsdir= $(datarootdir)/$(APP)/images/patterns
dist_patterns_DATA= share/diana/images/patterns/vertical.xpm \
	share/diana/images/patterns/vertical_broken.xpm \
	share/diana/images/patterns/squares.xpm \
	share/diana/images/patterns/solid.xpm \
	share/diana/images/patterns/sector_opposite-1.0.xpm \
	share/diana/images/patterns/sector_opposite-0.95.xpm \
	share/diana/images/patterns/sector_opposite-0.85.xpm \
	share/diana/images/patterns/sector_opposite-0.75.xpm \
	share/diana/images/patterns/sector_opposite-0.65.xpm \
	share/diana/images/patterns/sector_opposite-0.55.xpm \
	share/diana/images/patterns/sector_opposite-0.45.xpm \
	share/diana/images/patterns/sector_opposite-0.35.xpm \
	share/diana/images/patterns/sector_opposite-0.25.xpm \
	share/diana/images/patterns/sector_opposite-0.15.xpm \
	share/diana/images/patterns/sector_opposite-0.05.xpm \
	share/diana/images/patterns/sector-1.0.xpm \
	share/diana/images/patterns/sector-0.95.xpm \
	share/diana/images/patterns/sector-0.85.xpm \
	share/diana/images/patterns/sector-0.75.xpm \
	share/diana/images/patterns/sector-0.65.xpm \
	share/diana/images/patterns/sector-0.55.xpm \
	share/diana/images/patterns/sector-0.45.xpm \
	share/diana/images/patterns/sector-0.35.xpm \
	share/diana/images/patterns/sector-0.25.xpm \
	share/diana/images/patterns/sector-0.15.xpm \
	share/diana/images/patterns/sector-0.05.xpm \
	share/diana/images/patterns/horizontal.xpm \
	share/diana/images/patterns/empty.xpm \
	share/diana/images/patterns/dots.xpm \
	share/diana/images/patterns/dot_opposite-1.0.xpm \
	share/diana/images/patterns/dot_opposite-0.95.xpm \
	share/diana/images/patterns/dot_opposite-0.85.xpm \
	share/diana/images/patterns/dot_opposite-0.75.xpm \
	share/diana/images/patterns/dot_opposite-0.65.xpm \
	share/diana/images/patterns/dot_opposite-0.55.xpm \
	share/diana/images/patterns/dot_opposite-0.45.xpm \
	share/diana/images/patterns/dot_opposite-0.35.xpm \
	share/diana/images/patterns/dot_opposite-0.25.xpm \
	share/diana/images/patterns/dot_opposite-0.15.xpm \
	share/diana/images/patterns/dot_opposite-0.05.xpm \
	share/diana/images/patterns/dot-1.0.xpm \
	share/diana/images/patterns/dot-0.95.xpm \
	share/diana/images/patterns/dot-0.85.xpm \
	share/diana/images/patterns/dot-0.75.xpm \
	share/diana/images/patterns/dot-0.65.xpm \
	share/diana/images/patterns/dot-0.55.xpm \
	share/diana/images/patterns/dot-0.45.xpm \
	share/diana/images/patterns/dot-0.35.xpm \
	share/diana/images/patterns/dot-0.25.xpm \
	share/diana/images/patterns/dot-0.15.xpm \
	share/diana/images/patterns/dot-0.05.xpm \
	share/diana/images/patterns/diag.xpm \
	share/diana/images/patterns/diagthick.xpm \
	share/diana/images/patterns/diagthick1.xpm \
	share/diana/images/patterns/snowflake.xpm \
	share/diana/images/patterns/snowflake_cloud.xpm \
	share/diana/images/patterns/diagthick_cloud.xpm \
	share/diana/images/patterns/circles.xpm 

avatarsdir= $(datarootdir)/$(APP)/images/avatars
dist_avatars_DATA= share/diana/images/avatars/avatar_root.png \
	share/diana/images/avatars/avatar_lisbethb.png \
	share/diana/images/avatars/avatar_juergens.png \
	share/diana/images/avatars/avatar_bjornkl.png \
	share/diana/images/avatars/avatar_audunc.png

divdir= $(datarootdir)/$(APP)/
dist_div_DATA= share/diana/VNNsynop.list \
	share/diana/UK_lyn.header \
	share/diana/UALF_diana.header \
	share/diana/jason_swh.header \
	share/diana/synpltab.dat \
	share/diana/metpltab.dat \
	share/diana/radiofyr.txt \
	share/diana/printer.def \
	share/diana/priList.txt \
	share/diana/obsflag.html \
	share/diana/amdar.stations

