SET(METNO_QT_VERSION "5" CACHE STRING "Choose 4 for Qt4 or 5 for Qt5")

MACRO(METNO_FIND_QT components)
  SET(BUILDONLY FALSE)
  IF(METNO_QT_VERSION MATCHES 4)
    FOREACH(c ${ARGV})
      IF(${c} STREQUAL BUILDONLY)
        SET(BUILDONLY TRUE)
      ELSEIF(NOT "${c}" STREQUAL "PrintSupport")
        IF("${c}" STREQUAL "Widgets")
          SET(qt_comp "QtGui")
        ELSE()
          SET(qt_comp "Qt${c}")
        ENDIF()
        LIST(APPEND qt_components ${qt_comp})
        LIST(APPEND qt_libs "Qt4::${qt_comp}")
        IF (NOT BUILDONLY)
          LIST(APPEND METNO_PC_DEPS_QT ${qt_comp})
        ENDIF ()
      ENDIF ()
    ENDFOREACH()
    SET(METNO_QT_SUFFIX "")
  ELSEIF(METNO_QT_VERSION MATCHES 5)
    SET(METNO_QT_SUFFIX "-qt5")
    FOREACH(c ${ARGV})
      IF (${c} STREQUAL BUILDONLY)
        SET(BUILDONLY TRUE)
      ELSE ()
        LIST(APPEND qt_components ${c})
        LIST(APPEND qt_libs "Qt5::${c}")
        IF (NOT BUILDONLY)
          LIST(APPEND METNO_PC_DEPS_QT "Qt5${c}")
        ENDIF ()
      ENDIF ()
    ENDFOREACH()
    LIST(APPEND qt_components LinguistTools)
  ELSE()
    MESSAGE(SEND_ERROR "METNO_QT_VERSION should be 4 or 5")
  ENDIF()
  FIND_PACKAGE(Qt${METNO_QT_VERSION} REQUIRED COMPONENTS ${qt_components})
  SET(QT_LIBRARIES ${qt_libs})
ENDMACRO()

MACRO(METNO_QT_CREATE_TRANSLATION)
  IF(METNO_QT_VERSION MATCHES 4)
    QT4_CREATE_TRANSLATION(${ARGV})
  ELSEIF(METNO_QT_VERSION MATCHES 5)
    QT5_CREATE_TRANSLATION(${ARGV})
  ELSE()
    MESSAGE(SEND_ERROR "METNO_QT_VERSION should be 4 or 5")
  ENDIF()
ENDMACRO()
